# Generated by Django 3.2.1 on 2023-05-09 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('broker_host', models.CharField(default='redes2.ii.uam.es', max_length=100)),
                ('theme', models.CharField(default='redes2/2391/1/', max_length=100)),
                ('port', models.IntegerField(default=1883)),
                ('state', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('activator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='domotics.activator')),
                ('aid', models.IntegerField(default=uuid.UUID('1eebafe0-8c0b-4eca-abd3-0d8150da0f21'), primary_key=True, serialize=False)),
                ('time', models.CharField(default='20:40:14', max_length=255)),
                ('increment', models.IntegerField(default=1)),
                ('rate', models.IntegerField(default=1)),
            ],
            bases=('domotics.activator',),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('activator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='domotics.activator')),
                ('aid', models.IntegerField(default=uuid.UUID('b90b9e39-1f83-40a9-bb87-16042b65b496'), primary_key=True, serialize=False)),
                ('min', models.IntegerField(default=20)),
                ('max', models.IntegerField(default=30)),
                ('interval', models.IntegerField(default=1)),
                ('increment', models.IntegerField(default=1)),
            ],
            bases=('domotics.activator',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('activator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='domotics.activator')),
                ('aid', models.IntegerField(default=uuid.UUID('21323b2e-f734-4091-b1aa-0eddb662f221'), primary_key=True, serialize=False)),
                ('fail', models.FloatField(default=0.3)),
            ],
            bases=('domotics.activator',),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.CharField(default=None, max_length=255)),
                ('type', models.PositiveIntegerField(choices=[(0, 'LOWER'), (1, 'GREATER')], default=1)),
                ('description', models.CharField(default=None, max_length=255)),
                ('activator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domotics.activator')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_rules', to='domotics.switch')),
            ],
        ),
    ]
