# Generated by Django 3.2.1 on 2023-05-10 17:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('broker_host', models.CharField(default='redes2.ii.uam.es', max_length=100)),
                ('theme', models.CharField(default='redes2/2391/1/', max_length=100)),
                ('port', models.IntegerField(default=1883)),
                ('state', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('activator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='domotics.activator')),
                ('aid', models.IntegerField(default=uuid.UUID('249e619a-8c25-4f9c-aed4-fd68e0df5b8c'), primary_key=True, serialize=False)),
                ('time', models.CharField(default='19:15:23', max_length=255)),
                ('increment', models.IntegerField(default=1)),
                ('rate', models.IntegerField(default=1)),
            ],
            bases=('domotics.activator',),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('activator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='domotics.activator')),
                ('aid', models.IntegerField(default=uuid.UUID('ac1346f9-a8c0-4de9-8881-0153a116f86b'), primary_key=True, serialize=False)),
                ('min', models.IntegerField(default=20)),
                ('max', models.IntegerField(default=30)),
                ('interval', models.IntegerField(default=1)),
                ('increment', models.IntegerField(default=1)),
            ],
            bases=('domotics.activator',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('activator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='domotics.activator')),
                ('aid', models.IntegerField(default=uuid.UUID('84f5c8cf-9184-4db6-bfbf-8f0027676b9c'), primary_key=True, serialize=False)),
                ('fail', models.FloatField(default=0.3)),
            ],
            bases=('domotics.activator',),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.CharField(default=None, max_length=255)),
                ('type', models.PositiveIntegerField(choices=[(0, 'LOWER'), (1, 'GREATER')], default=1)),
                ('description', models.CharField(default=None, max_length=255)),
                ('activator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domotics.activator')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_rules', to='domotics.switch')),
            ],
        ),
    ]
